/** @module challenge.main */require( 'challenge.main', function(require, module, exports) { var _=function(){var D={"en":{},"fr":{}},X=require("$").intl;function _(){return X(D,arguments);}_.all=D;return _}();
    // Code behind.
"use strict";

var CODE_BEHIND = {
  init: init,
  keydown: keydown,
  onCursorChanged: onCursorChanged,
  mapChallenges: mapChallenges
};


var $ = require("dom");


function init() {
  window.setInterval( checkMove.bind( this ), 500 );
}

function keydown( rawKey ) {
  var key = rawKey.toUpperCase();
  console.info("[challenge.main] key=", key);
  switch( key ) {
  case 'A':
    this.challenge = 'anagram';
    break;
  case 'B':
    this.challenge = 'twister';
    break;
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
    if( this.die > 0 ) return;
    this.bounce = false;
    this.die = key;
    break;
  case '6':
    // We stay where we are, but we start the challenge.
    this.challenge = this.challenges[this.cursor];
    break;
  }
}


function mapChallenges( challenge ) {
  return $.div( "challenge", "thm-ele12", challenge );
}


/**
 * Every 300 ms, we must advance the `cursor` if there is still `die` > 0.
 */
function checkMove() {
  if( this.die < 1 ) return;

  this.die--;
  var dir = 0;
  if( this.forward ) dir = this.bounce ? -1 : 1;
  else dir = this.bounce ? 1 : -1;

  var cursor = this.cursor + dir;
  if( cursor < 0 || cursor >= this.challenges.length ) {
    // Bouncing on an edge.
    this.bounce = true;
    cursor = this.cursor - dir;
  }
  this.cursor = cursor;
  
  if( this.die === 0 ) {
    // End of the die travel. We go to the selected challenge.
    var that = this;
    window.setTimeout(function() {
      that.challenge = that.challenges[cursor];
    }, 500);
  }
}


function onCursorChanged( cursor ) {
  $.css( this.$elements.strip, {
    transform: "translateX(" + (30 - cursor * 15) + "vw)"
  });
}


//===============================
// XJS:View autogenerated code.
try {
  module.exports = function() {
    //--------------------
    // Dependent modules.
    var $ = require('dom');
    var PM = require('tfw.binding.property-manager');
    var Tag = require('tfw.view').Tag;
    var Link = require('tfw.binding.link');
    var View = require('tfw.view');;
    var Converters = require('tfw.binding.converters');
    //-------------------------------------------------------
    // Check if needed functions are defined in code behind.
    View.ensureCodeBehind( CODE_BEHIND, "onCursorChanged", "keydown", "init", "mapChallenges" );
    //-------------------
    // Global functions.
    function defVal(args, attName, attValue) { return args[attName] === undefined ? attValue : args[attName]; };
    //-------------------
    // Global variables.
    var conv_array = Converters.get('array');
    var conv_integer = Converters.get('integer');
    var conv_boolean = Converters.get('boolean');
    //-------------------
    // Class definition.
    var ViewClass = function( args ) {
      try {
        if( typeof args === 'undefined' ) args = {};
        this.$elements = {};
        var that = this;
        var pm = PM(this);
        //--------------------
        // Create attributes.
        pm.create("challenges", { cast: conv_array });
        pm.createAction("challenge")
        pm.create("cursor", { cast: conv_integer(0) });
        pm.create("die", { cast: conv_integer(0) });
        pm.create("forward", { cast: conv_boolean });
        pm.create("bounce", { cast: conv_boolean });
        //------------------
        // Create elements.
        var e_ = new Tag('DIV', ["class"]);
        var e_0 = new Tag('DIV', ["class"]);
        var e_strip = new Tag('DIV', ["class"]);
        this.$elements.strip = e_strip;
        var e_2 = new Tag('DIV', ["class"]);
        $.add( e_0, e_strip, e_2 );
        var e_3 = new Tag('DIV', ["class","innerhtml"]);
        $.add( e_, e_0, e_3 );
        //-----------------------
        // Declare root element.
        Object.defineProperty( this, '$', {value: e_.$, writable: false, enumerable: false, configurable: false } );
        //-------
        // Links
        new Link({
          A:{obj: that,
              name: 'challenges'},
          B:{action: function(v) {
          // Updating children of e_strip.
          $.clear(e_strip);
          if( !Array.isArray( v ) ) v = [v];
          v.forEach(function (elem) {
            $.add(e_strip, elem);
          });},
              map: function() {
          return CODE_BEHIND.mapChallenges.apply(that, arguments)}},
          name:"challenges > undefined"
        });
        //-----------------------
        // On attribute changed.
        pm.on( "cursor", function(v) {
          try {
            CODE_BEHIND.onCursorChanged.call( that, v );
          }
          catch( ex ) {
            console.error('Exception in function behind "onCursorChanged" of module "mod/challenge.main.js" for attribute "cursor"!  ');
            console.error( ex );
          }} );
        //----------------------
        // Initialize elements.
        e_.class = "challenge-main";
        e_0.class = "strip-container";
        e_strip.class = "strip";
        e_2.class = "cursor";
        e_3.class = "shadowFFF";
        e_3.innerhtml = "Lancez un dé à 6 faces et tapez le chiffre obtenu.";
        //------------------------
        // Initialize attributes.
        this.challenges = defVal(args, "challenges", ["nim","paper","anagram","twister","taquin","nim","paper","anagram","twister","taquin","nim","victory"]);
        this.cursor = defVal(args, "cursor", 0);
        this.die = defVal(args, "die", 0);
        this.forward = defVal(args, "forward", true);
        this.bounce = defVal(args, "bounce", false);
        // Initialization.
        CODE_BEHIND.init.call( this );
        $.addClass(this, 'view', 'custom');
      }
      catch( ex ) {
        console.error('mod/challenge.main.js', ex);
        throw Error('Instantiation error in XJS of "mod/challenge.main.js":\n' + ex)
      }
    };
    //------------------
    // Static members..
    ViewClass.prototype.keydown = CODE_BEHIND.keydown;
    return ViewClass;
  }();
}
catch( ex ) {
  throw Error('Definition error in XJS of "mod/challenge.main.js"\n' + ex)
}


  
module.exports._ = _;
/**
 * @module challenge.main
 * @see module:$
 * @see module:dom
 * @see module:dom
 * @see module:tfw.binding.property-manager
 * @see module:tfw.view
 * @see module:tfw.binding.link
 * @see module:tfw.view
 * @see module:tfw.binding.converters

 */
});